<?php
$patients = is_array($patients ?? null) ? $patients : [];
$keyword = (string) ($keyword ?? '');
$status = (string) ($status ?? '');
function pv_i_e(mixed $value): string { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }
function pv_i_name(array $row): string { return trim(($row['first_name'] ?? '') . ' ' . ($row['middle_name'] ?? '') . ' ' . ($row['last_name'] ?? '')) ?: 'Unnamed patient'; }
ob_start();
?>
<style>.pv-page{padding:24px 16px 42px;background:#f5f6f8;min-height:100vh}.pv-wrap{max-width:1180px;margin:auto}.pv-card{background:#fff;border:1px solid #e5e7eb;padding:22px;box-shadow:0 8px 26px rgba(15,23,42,.04)}.pv-title{margin:0;color:#10233f;font-size:24px}.pv-copy{color:#64748b}.pv-tools{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.pv-tools input,.pv-tools select{min-height:40px;border:1px solid #cbd5e1;padding:0 10px}.pv-btn{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 14px;border:0;background:#0d9e8c;color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.pv-table{width:100%;border-collapse:collapse}.pv-table th,.pv-table td{padding:12px 10px;border-bottom:1px solid #e5e7eb;text-align:left;font-size:13px}.pv-badge{display:inline-flex;padding:4px 9px;border-radius:999px;background:#eef2ff;color:#3730a3;font-weight:800;font-size:11px}.pv-empty{padding:28px;text-align:center;color:#64748b}@media(max-width:760px){.pv-card{overflow:auto}.pv-table{min-width:760px}}
</style>
<div class="pv-page"><div class="pv-wrap"><section class="pv-card"><h1 class="pv-title">Patient Verification</h1><p class="pv-copy">Review submitted patient information, connect accounts, and record an auditable decision.</p>
<form class="pv-tools" method="GET" action="/DentalClinic/public/staff/patient-verification"><input name="keyword" placeholder="Search name, email, phone, code" value="<?= pv_i_e($keyword) ?>"><select name="status"><option value="">All statuses</option><?php foreach(['incomplete','submitted','requires_update','approved','rejected'] as $option): ?><option value="<?= $option ?>" <?= $status === $option ? 'selected' : '' ?>><?= ucwords(str_replace('_',' ',$option)) ?></option><?php endforeach; ?></select><button class="pv-btn">Filter</button></form>
<table class="pv-table"><thead><tr><th>Patient</th><th>Email</th><th>Contact</th><th>Account</th><th>Status</th><th>Action</th></tr></thead><tbody><?php if (!$patients): ?><tr><td colspan="6" class="pv-empty">No patient records found.</td></tr><?php endif; ?><?php foreach($patients as $row): ?><tr><td><strong><?= pv_i_e(pv_i_name($row)) ?></strong><br><small><?= pv_i_e($row['patient_code'] ?? '') ?></small></td><td><?= pv_i_e($row['email'] ?? '') ?></td><td><?= pv_i_e($row['contact_number'] ?? '') ?></td><td><?= !empty($row['linked_user_id']) ? 'Connected' : 'No user account' ?></td><td><span class="pv-badge"><?= pv_i_e(ucwords(str_replace('_',' ',(string)($row['verification_status'] ?? 'incomplete')))) ?></span></td><td><a class="pv-btn" href="/DentalClinic/public/staff/patient-verification/show?id=<?= (int)$row['patient_id'] ?>">Review</a></td></tr><?php endforeach; ?></tbody></table></section></div></div>
<?php $content = ob_get_clean(); $pageTitle = 'Patient Verification'; require __DIR__ . '/../layouts/app.php';
