<?php
use App\Core\Csrf;
$patient = is_array($patient ?? null) ? $patient : [];
$medicalHistory = is_array($medicalHistory ?? null) ? $medicalHistory : [];
$dentalHistory = is_array($dentalHistory ?? null) ? $dentalHistory : [];
$possibleUser = is_array($possibleUser ?? null) ? $possibleUser : null;
function pv_s_e(mixed $value): string { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }
function pv_s_name(array $row): string { return trim(($row['first_name'] ?? '') . ' ' . ($row['middle_name'] ?? '') . ' ' . ($row['last_name'] ?? '')) ?: 'Unnamed patient'; }
function pv_s_value(mixed $value): string { $value = trim((string) $value); return $value === '' ? 'Not provided' : nl2br(pv_s_e($value)); }
ob_start();
?>
<?php if ($possibleUser): ?>
<div class="pvs-card"><h2>Possible Existing User Account</h2><p class="pvs-copy">An account matched this patient's email or contact number. Confirm the connection explicitly; patient history will not be overwritten.</p><div class="pvs-item"><strong><?= pv_s_e(pv_s_name($possibleUser)) ?></strong><br><?= pv_s_e($possibleUser['email'] ?? '') ?><br><?= pv_s_e($possibleUser['contact_number'] ?? '') ?></div><form method="POST" action="/DentalClinic/public/staff/patient-verification/connect-user" style="margin-top:12px"><input type="hidden" name="patient_id" value="<?= (int)$patient['patient_id'] ?>"><input type="hidden" name="user_id" value="<?= (int)$possibleUser['user_id'] ?>"><?= Csrf::inputField() ?><button class="pvs-btn secondary" type="submit" onclick="return confirm('Connect this existing user account to this patient record?')">Connect User Account</button></form></div>
<?php endif; ?>
<style>.pvs-page{padding:24px 16px 42px;background:#f5f6f8;min-height:100vh}.pvs-wrap{max-width:1000px;margin:auto}.pvs-card{background:#fff;border:1px solid #e5e7eb;padding:22px;margin-bottom:16px;box-shadow:0 8px 26px rgba(15,23,42,.04)}.pvs-title{margin:0;color:#10233f}.pvs-copy{color:#64748b}.pvs-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.pvs-item{padding:12px;background:#f8fafc;border:1px solid #edf2f7}.pvs-label{display:block;font-size:11px;text-transform:uppercase;color:#64748b;font-weight:800;margin-bottom:4px}.pvs-value{font-size:14px;line-height:1.6;color:#1f2937}.pvs-alert{padding:12px;background:#ecfdf5;color:#065f46;margin-bottom:14px}.pvs-actions{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.pvs-actions form{display:grid;gap:7px}.pvs-actions textarea{min-width:260px;min-height:70px;border:1px solid #cbd5e1;padding:8px}.pvs-btn{min-height:40px;border:0;padding:0 14px;background:#0d9e8c;color:#fff;font-weight:800;cursor:pointer}.pvs-btn.warn{background:#d97706}.pvs-btn.danger{background:#dc2626}.pvs-btn.secondary{background:#334155;text-decoration:none;display:inline-flex;align-items:center}.pvs-table{width:100%;border-collapse:collapse}.pvs-table td{padding:9px;border-bottom:1px solid #e5e7eb;vertical-align:top}.pvs-back{display:inline-flex;margin-bottom:14px;color:#0f766e;font-weight:800;text-decoration:none}@media(max-width:700px){.pvs-grid{grid-template-columns:1fr}.pvs-actions form{width:100%}.pvs-actions textarea{width:100%;min-width:0}}
</style>
<div class="pvs-page"><div class="pvs-wrap"><a class="pvs-back" href="/DentalClinic/public/staff/patient-verification">&larr; Patient Verification</a><?php if($flash_success ?? null): ?><div class="pvs-alert"><?= pv_s_e($flash_success) ?></div><?php endif; ?><?php if($flash_error ?? null): ?><div class="pvs-alert" style="background:#fef2f2;color:#991b1b"><?= pv_s_e($flash_error) ?></div><?php endif; ?>
<section class="pvs-card"><h1 class="pvs-title"><?= pv_s_e(pv_s_name($patient)) ?></h1><p class="pvs-copy">Patient record <?= pv_s_e($patient['patient_code'] ?? '') ?>. Current status: <strong><?= pv_s_e(ucwords(str_replace('_',' ',(string)($patient['verification_status'] ?? 'incomplete')))) ?></strong></p><div class="pvs-grid"><div class="pvs-item"><span class="pvs-label">Email</span><div class="pvs-value"><?= pv_s_value($patient['email'] ?? '') ?></div></div><div class="pvs-item"><span class="pvs-label">Contact</span><div class="pvs-value"><?= pv_s_value($patient['contact_number'] ?? '') ?></div></div><div class="pvs-item"><span class="pvs-label">Birth date</span><div class="pvs-value"><?= pv_s_value($patient['birth_date'] ?? '') ?></div></div><div class="pvs-item"><span class="pvs-label">Address</span><div class="pvs-value"><?= pv_s_value($patient['address'] ?? '') ?></div></div><div class="pvs-item"><span class="pvs-label">Linked user</span><div class="pvs-value"><?= !empty($patient['linked_user_id']) ? 'Yes (#'.(int)$patient['linked_user_id'].')' : 'No user account' ?></div></div><div class="pvs-item"><span class="pvs-label">Submitted</span><div class="pvs-value"><?= pv_s_value($patient['verification_submitted_at'] ?? '') ?></div></div></div></section>
<section class="pvs-card"><h2>Medical History</h2><table class="pvs-table"><?php foreach($medicalHistory as $key=>$value): if(in_array($key,['medical_history_id','patient_id','updated_by','created_at','updated_at'],true)) continue; ?><tr><td class="pvs-label"><?= pv_s_e(ucwords(str_replace('_',' ',$key))) ?></td><td><?= pv_s_value($value) ?></td></tr><?php endforeach; ?></table></section>
<section class="pvs-card"><h2>Dental History</h2><table class="pvs-table"><?php foreach($dentalHistory as $key=>$value): if(in_array($key,['dental_history_id','patient_id','updated_by','created_at','updated_at'],true)) continue; ?><tr><td class="pvs-label"><?= pv_s_e(ucwords(str_replace('_',' ',$key))) ?></td><td><?= pv_s_value($value) ?></td></tr><?php endforeach; ?></table></section>
<section class="pvs-card"><h2>Review Decision</h2><div class="pvs-actions"><form method="POST" action="/DentalClinic/public/staff/patient-verification/status"><input type="hidden" name="patient_id" value="<?= (int)$patient['patient_id'] ?>"><?= Csrf::inputField() ?><textarea name="verification_notes" placeholder="Optional for approval; required for update/rejection"><?= pv_s_e($patient['verification_notes'] ?? '') ?></textarea><input type="hidden" name="verification_status" value="approved"><button class="pvs-btn" type="submit">Confirm Patient</button></form><form method="POST" action="/DentalClinic/public/staff/patient-verification/status"><input type="hidden" name="patient_id" value="<?= (int)$patient['patient_id'] ?>"><?= Csrf::inputField() ?><textarea name="verification_notes" required placeholder="Explain what must be updated"></textarea><input type="hidden" name="verification_status" value="requires_update"><button class="pvs-btn warn" type="submit">Request Update</button></form><form method="POST" action="/DentalClinic/public/staff/patient-verification/status"><input type="hidden" name="patient_id" value="<?= (int)$patient['patient_id'] ?>"><?= Csrf::inputField() ?><textarea name="verification_notes" required placeholder="Reason for rejection"></textarea><input type="hidden" name="verification_status" value="rejected"><button class="pvs-btn danger" type="submit">Reject</button></form><?php if(empty($patient['linked_user_id'])): ?><form method="POST" action="/DentalClinic/public/staff/patient-verification/invite"><input type="hidden" name="patient_id" value="<?= (int)$patient['patient_id'] ?>"><?= Csrf::inputField() ?><button class="pvs-btn secondary" type="submit">Invite Patient</button></form><?php endif; ?></div></section>
</div></div>
<?php $content = ob_get_clean(); $pageTitle = 'Review Patient'; require __DIR__ . '/../layouts/app.php';
